apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.metadata.name }}
  name: {{.Release.Name}}-{{ .Values.metadata.name }}
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.metadata.name }}
  type: NodePort
status:
  loadBalancer: {}
